In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.6.0+cu124


Introduction to tensor

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

#TENSOR

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [3,6,7],
                        [10,22,32]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5],
         [ 3,  6,  7],
         [10, 22, 32]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 5, 3])

In [16]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [ 2,  4,  5],
        [ 3,  6,  7],
        [10, 22, 32]])

RANDOM TENSORS

the way many neural networks with is starting eith random numbers and then updating then

In [17]:
random_tensor = torch.rand(3, 4, 5)

In [18]:
random_tensor

tensor([[[0.3436, 0.0862, 0.6417, 0.8993, 0.9006],
         [0.9637, 0.3748, 0.1256, 0.9854, 0.6261],
         [0.9855, 0.7761, 0.5254, 0.7709, 0.1991],
         [0.8123, 0.3009, 0.6661, 0.7434, 0.3224]],

        [[0.4652, 0.3228, 0.9504, 0.0307, 0.6265],
         [0.9334, 0.1232, 0.0762, 0.0441, 0.9080],
         [0.6605, 0.0608, 0.8457, 0.2269, 0.7082],
         [0.8372, 0.7991, 0.3324, 0.8754, 0.6612]],

        [[0.4014, 0.1291, 0.4446, 0.0913, 0.6130],
         [0.5027, 0.4969, 0.7391, 0.8650, 0.7977],
         [0.3041, 0.3768, 0.5934, 0.9767, 0.7845],
         [0.1592, 0.8687, 0.7407, 0.1815, 0.9359]]])

In [19]:
random_tensor.ndim

3

In [20]:
random_tensor.shape

torch.Size([3, 4, 5])

CREATE A RANDOM TENSOR SIMILAR TO AN IMAGE

In [21]:
random_image_tensor = torch.rand(224, 224, 3) #height, width, color

In [22]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [23]:
random_image_tensor.ndim

3

In [24]:
r_tensor = torch.rand(size = (1,10,10))

In [25]:
r_tensor

tensor([[[0.1080, 0.3912, 0.1062, 0.9880, 0.2207, 0.1949, 0.8376, 0.0797,
          0.8393, 0.8477],
         [0.2627, 0.8381, 0.8030, 0.7417, 0.7757, 0.8672, 0.2298, 0.5443,
          0.1014, 0.2399],
         [0.0471, 0.2764, 0.1827, 0.0055, 0.5294, 0.0942, 0.4543, 0.3605,
          0.3468, 0.5687],
         [0.6347, 0.3127, 0.3242, 0.7261, 0.7760, 0.1672, 0.1426, 0.9045,
          0.3499, 0.2604],
         [0.1964, 0.3971, 0.9885, 0.2156, 0.7422, 0.0913, 0.0736, 0.8617,
          0.6513, 0.6217],
         [0.3204, 0.1060, 0.3821, 0.6212, 0.9110, 0.0186, 0.0470, 0.8458,
          0.5938, 0.1224],
         [0.5776, 0.3805, 0.8911, 0.1710, 0.6009, 0.4436, 0.2407, 0.3850,
          0.8130, 0.5904],
         [0.0129, 0.8963, 0.2292, 0.9183, 0.7753, 0.7480, 0.3738, 0.0975,
          0.8789, 0.4928],
         [0.6035, 0.8060, 0.8294, 0.8649, 0.9127, 0.2603, 0.7191, 0.0281,
          0.4155, 0.5548],
         [0.1502, 0.5705, 0.5531, 0.5462, 0.9606, 0.9569, 0.6162, 0.1145,
          0.4311,

### Zeros and ones

In [26]:
zero = torch.zeros(size = (1,10,10))

In [27]:
zero

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [28]:
r_tensor = zero + r_tensor
r_tensor

tensor([[[0.1080, 0.3912, 0.1062, 0.9880, 0.2207, 0.1949, 0.8376, 0.0797,
          0.8393, 0.8477],
         [0.2627, 0.8381, 0.8030, 0.7417, 0.7757, 0.8672, 0.2298, 0.5443,
          0.1014, 0.2399],
         [0.0471, 0.2764, 0.1827, 0.0055, 0.5294, 0.0942, 0.4543, 0.3605,
          0.3468, 0.5687],
         [0.6347, 0.3127, 0.3242, 0.7261, 0.7760, 0.1672, 0.1426, 0.9045,
          0.3499, 0.2604],
         [0.1964, 0.3971, 0.9885, 0.2156, 0.7422, 0.0913, 0.0736, 0.8617,
          0.6513, 0.6217],
         [0.3204, 0.1060, 0.3821, 0.6212, 0.9110, 0.0186, 0.0470, 0.8458,
          0.5938, 0.1224],
         [0.5776, 0.3805, 0.8911, 0.1710, 0.6009, 0.4436, 0.2407, 0.3850,
          0.8130, 0.5904],
         [0.0129, 0.8963, 0.2292, 0.9183, 0.7753, 0.7480, 0.3738, 0.0975,
          0.8789, 0.4928],
         [0.6035, 0.8060, 0.8294, 0.8649, 0.9127, 0.2603, 0.7191, 0.0281,
          0.4155, 0.5548],
         [0.1502, 0.5705, 0.5531, 0.5462, 0.9606, 0.9569, 0.6162, 0.1145,
          0.4311,

In [29]:
ones = torch.ones(size = (1, 10, 10))

In [30]:
ones

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [31]:
r_tensor = r_tensor + ones

In [32]:
r_tensor

tensor([[[1.1080, 1.3912, 1.1062, 1.9880, 1.2207, 1.1949, 1.8376, 1.0797,
          1.8393, 1.8477],
         [1.2627, 1.8381, 1.8030, 1.7417, 1.7757, 1.8672, 1.2298, 1.5443,
          1.1014, 1.2399],
         [1.0471, 1.2764, 1.1827, 1.0055, 1.5294, 1.0942, 1.4543, 1.3605,
          1.3468, 1.5687],
         [1.6347, 1.3127, 1.3242, 1.7261, 1.7760, 1.1672, 1.1426, 1.9045,
          1.3499, 1.2604],
         [1.1964, 1.3971, 1.9885, 1.2156, 1.7422, 1.0913, 1.0736, 1.8617,
          1.6513, 1.6217],
         [1.3204, 1.1060, 1.3821, 1.6212, 1.9110, 1.0186, 1.0470, 1.8458,
          1.5938, 1.1224],
         [1.5776, 1.3805, 1.8911, 1.1710, 1.6009, 1.4436, 1.2407, 1.3850,
          1.8130, 1.5904],
         [1.0129, 1.8963, 1.2292, 1.9183, 1.7753, 1.7480, 1.3738, 1.0975,
          1.8789, 1.4928],
         [1.6035, 1.8060, 1.8294, 1.8649, 1.9127, 1.2603, 1.7191, 1.0281,
          1.4155, 1.5548],
         [1.1502, 1.5705, 1.5531, 1.5462, 1.9606, 1.9569, 1.6162, 1.1145,
          1.4311,

Create tensors of range

In [33]:
range_tensor = torch.arange(start = 0, end = 100, step = 2)
range_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [34]:
r2 = torch.zeros_like(input = range_tensor)
r2

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

TENSOR DATATYPE

***Issues you would run into***
1.Tensor not right data type
2.Tensor not right shape
3.Tensor not ont the right device

In [35]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype =torch.float32, #datatype of tensor
                               device = None,#Device tensor on
                               requires_grad=False)#to track gradient or not
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
float_32_tensor.shape

torch.Size([3])

In [38]:
  float_16_tensor = float_32_tensor.type(torch.float16)
  float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
float_32_tensor.dtype

torch.float32

In [40]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

Sometimes bring different data types it still works

In [41]:
tensor_int = torch.rand(3,4)

In [42]:
tensor_int

tensor([[0.8544, 0.2415, 0.5702, 0.4659],
        [0.8254, 0.2907, 0.6862, 0.3529],
        [0.8345, 0.7785, 0.9818, 0.5894]])

**Giving the same shape and data type as float_16_tensor**

In [43]:
tensor_int = torch.rand(float_16_tensor.shape).type(torch.float16)

In [44]:
tensor_int * float_32_tensor

tensor([0.1435, 2.5254, 1.3799])

In [45]:
f1 = torch.tensor([1, 2, 3],
                  dtype=torch.int32)
f2 = torch.tensor([2, 6, 8], dtype=torch.int64)

In [46]:
f1 * f2

tensor([ 2, 12, 24])

In [47]:
f1.dtype

torch.int32

In [48]:
f1 = f1.to("cuda")
f1.device

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

#Gettting information from tensors

In [49]:
t1 = torch.rand(3,3)
t1

tensor([[0.4117, 0.1564, 0.4267],
        [0.7678, 0.9533, 0.6562],
        [0.3820, 0.1633, 0.9232]])

In [50]:
print(t1)

tensor([[0.4117, 0.1564, 0.4267],
        [0.7678, 0.9533, 0.6562],
        [0.3820, 0.1633, 0.9232]])


In [51]:
t1 = t1.to(dtype=torch.int16)
t1=t1.to(device="cuda")

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [52]:
print(f"data type: {t1.dtype}")
print(f"shape of tensor: {t1.size()}")
print(f"dimension of tensor: {t1.ndim}")
print(f"Device: {t1.device}")

data type: torch.int16
shape of tensor: torch.Size([3, 3])
dimension of tensor: 2
Device: cpu


In [53]:
 t1 = torch.rand(3,3)
 t1

tensor([[0.0994, 0.8656, 0.2830],
        [0.7332, 0.3702, 0.4374],
        [0.4213, 0.1782, 0.2062]])

In [54]:
t1 + 10

tensor([[10.0994, 10.8656, 10.2830],
        [10.7332, 10.3702, 10.4374],
        [10.4213, 10.1782, 10.2062]])

In [55]:
t1 * 2

tensor([[0.1989, 1.7312, 0.5661],
        [1.4665, 0.7404, 0.8747],
        [0.8426, 0.3565, 0.4124]])

In [56]:
t1 * 0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Tensor operations
1. Addition
2. Substraction
3. multiplication
4. Division
5. Matrix multiplication


In [57]:
t = torch.tensor([1, 2, 3],
                dtype=torch.float32,
                device="cuda")

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [58]:
 t = t + 10
 t

NameError: name 't' is not defined

In [59]:
t = t * 10
t

NameError: name 't' is not defined

In [60]:
t = t-100
t

NameError: name 't' is not defined

In [61]:
t=torch.mul(t,10)
t

NameError: name 't' is not defined

In [62]:
t=torch.add(t,10)
t

NameError: name 't' is not defined

In [63]:
t

NameError: name 't' is not defined

MATRIX MULTIPLICATION

1. Element wise
2. Matrix Multiplication

In [64]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [65]:
t * t

tensor([1, 4, 9])

MAtrix multiplication

In [66]:
torch.matmul(t,t)

tensor(14)

In [67]:
1*1 + 2*2 + 3*3

14

In [68]:
%%time
value = 0
for i in range (len(t)):
  value += t[i] * t[i]
print(value)

tensor(14)
CPU times: user 1.96 ms, sys: 0 ns, total: 1.96 ms
Wall time: 1.87 ms


In [69]:
%%time
torch.matmul(t,t)

CPU times: user 389 µs, sys: 65 µs, total: 454 µs
Wall time: 359 µs


tensor(14)

In [70]:
tensor=torch.rand(3,2)
tensor.shape

torch.Size([3, 2])

In [71]:
tensor=tensor.reshape(2,3)

In [72]:
torch.matmul(torch.rand(4,30), torch.rand(30,2)).shape

torch.Size([4, 2])

In [73]:
tensor_A = torch.tensor(([1,2],
                        [3,4],
                         [5,6]))
tensor_B = torch.tensor(([1,2],
                        [3,4],
                         [5,6]))
print(tensor_A.shape)
print(tensor_B.shape)
tensor_B = tensor_B.reshape(2,3)
print(tensor_B.shape)
torch.matmul(tensor_A, tensor_B)

torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([2, 3])


tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [80]:
tensor_B = tensor_B.T

In [81]:
tensor_B.shape

torch.Size([2, 3])

In [82]:
tensor_B

tensor([[1, 2, 3],
        [4, 5, 6]])

In [83]:
torch.mm(tensor_A, tensor_B)

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

FINDING min, max, mean, sum

In [84]:
x = torch.arange(10,0,-1)

In [85]:
x

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [86]:
torch.max(x)

tensor(10)

In [87]:
x.max()

tensor(10)

In [88]:
x.min()

tensor(1)

In [89]:
torch.min(x)

tensor(1)

In [90]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [91]:
x.dtype

torch.int64

**Doesnt work beacause data type isn't supported**

In [95]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(5.5000), tensor(5.5000))

In [96]:
torch.sum(x), x.sum()

(tensor(55), tensor(55))

In [97]:
x.argmin() #Return position of min value

tensor(9)

In [98]:
x[9]

tensor(1)

In [99]:
x.argmax() #return position of maximum value

tensor(0)

In [100]:
x[x.argmax()]

tensor(10)

 **Reshaping, Stacking, Squeezing, Unsqueezing**

  * Reshape - reshape input tensor to a defined shape
  * View - Return view of an input tensor of cetian shape but keep the same memory as the original Shape
  * stack - combine multiple tensors on top of each other(vstack) or side by side(hstack)
  * squeeze - remove all 1 Dimensiond from a tensor
  * unsqueeze - adds a 1 dimension to a target tensor
  * permute- retrun a view of the input with dimensions permuted(swapped) in
    certain way

In [183]:
x_tensor = torch.arange(1., 100., 10,dtype=torch.float32)
x_tensor.shape

torch.Size([10])

In [184]:
x_tensor

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

In [185]:
#Add extra dimension
x_reshape = x.reshape(5,2)
x_reshape

tensor([[10,  9],
        [ 8,  7],
        [ 6,  5],
        [ 4,  3],
        [ 2,  1]])

In [186]:
#Change the view
z = x_tensor.view(5, 2)
z, z.shape,

(tensor([[ 1., 11.],
         [21., 31.],
         [41., 51.],
         [61., 71.],
         [81., 91.]]),
 torch.Size([5, 2]))

In [187]:
z[:, 0] = 5
x_tensor, z

(tensor([ 5., 11.,  5., 31.,  5., 51.,  5., 71.,  5., 91.]),
 tensor([[ 5., 11.],
         [ 5., 31.],
         [ 5., 51.],
         [ 5., 71.],
         [ 5., 91.]]))

In [188]:
#stack tensor on top

x_stacked = torch.stack([z,z,z,z],dim=2)
x_stacked

tensor([[[ 5.,  5.,  5.,  5.],
         [11., 11., 11., 11.]],

        [[ 5.,  5.,  5.,  5.],
         [31., 31., 31., 31.]],

        [[ 5.,  5.,  5.,  5.],
         [51., 51., 51., 51.]],

        [[ 5.,  5.,  5.,  5.],
         [71., 71., 71., 71.]],

        [[ 5.,  5.,  5.,  5.],
         [91., 91., 91., 91.]]])

In [189]:
#stack tensor on top

x_stacked = torch.hstack([z,z,z,z])
x_stacked

tensor([[ 5., 11.,  5., 11.,  5., 11.,  5., 11.],
        [ 5., 31.,  5., 31.,  5., 31.,  5., 31.],
        [ 5., 51.,  5., 51.,  5., 51.,  5., 51.],
        [ 5., 71.,  5., 71.,  5., 71.,  5., 71.],
        [ 5., 91.,  5., 91.,  5., 91.,  5., 91.]])

In [190]:
#stack tensor on top

x_stacked = torch.vstack([z,z,z,z])
x_stacked

tensor([[ 5., 11.],
        [ 5., 31.],
        [ 5., 51.],
        [ 5., 71.],
        [ 5., 91.],
        [ 5., 11.],
        [ 5., 31.],
        [ 5., 51.],
        [ 5., 71.],
        [ 5., 91.],
        [ 5., 11.],
        [ 5., 31.],
        [ 5., 51.],
        [ 5., 71.],
        [ 5., 91.],
        [ 5., 11.],
        [ 5., 31.],
        [ 5., 51.],
        [ 5., 71.],
        [ 5., 91.]])

In [224]:
y = torch.rand(1,3)

In [232]:
print(f"Previous tensor: {y}")

Previous tensor:tensor([[0.2355, 0.8345, 0.5806]])


In [233]:
print(f"shape: {y.shape}")

shape:torch.Size([1, 3])


In [236]:
torch.squeeze(y), torch.squeeze(y).shape
y = torch.squeeze(y)

In [256]:
y.unsqueeze(dim=1)

tensor([[0.2355],
        [0.8345],
        [0.5806]])

In [259]:
y= y.squeeze()
y

tensor([0.2355, 0.8345, 0.5806])

# PERMUTE

In [280]:
 x_tensor = torch.rand(size=(224, 224, 3))

 #Permute the original tensor to rearrange the axis of dim order

 x_per = x_tensor.permute(0, 2, 1)

In [281]:
x_tensor.shape

torch.Size([224, 224, 3])

In [282]:
x_tensor[0, 0, 0] = 12345

In [284]:
x_per[0, 0, 0]

tensor(12345.)

In [286]:
x_per

tensor([[[1.2345e+04, 9.4331e-01, 6.8659e-01,  ..., 9.5339e-01,
          4.9703e-02, 9.1501e-01],
         [5.0001e-01, 8.9434e-01, 1.0690e-01,  ..., 3.8132e-01,
          5.7973e-01, 6.6276e-01],
         [8.7297e-01, 4.5515e-01, 1.6828e-02,  ..., 1.5363e-01,
          4.3766e-01, 2.3118e-01]],

        [[5.1984e-02, 1.4286e-01, 2.2137e-01,  ..., 3.2216e-01,
          7.9386e-01, 2.7695e-01],
         [2.7259e-01, 2.0804e-01, 6.9228e-01,  ..., 9.7330e-01,
          8.8394e-01, 9.6839e-01],
         [4.9940e-01, 9.8815e-01, 5.9005e-01,  ..., 5.2780e-01,
          9.3389e-01, 3.4333e-02]],

        [[1.3029e-01, 1.7709e-01, 5.9625e-01,  ..., 6.4821e-01,
          2.6158e-01, 8.9489e-01],
         [9.8543e-01, 3.6936e-01, 5.3701e-01,  ..., 5.2067e-01,
          5.8988e-01, 6.3474e-01],
         [5.9239e-01, 2.3993e-01, 2.4049e-01,  ..., 7.6215e-01,
          1.0933e-01, 7.8842e-01]],

        ...,

        [[1.3692e-01, 5.4274e-01, 5.1450e-01,  ..., 2.7175e-01,
          3.3548e-01, 7.5

# Indexing (Selecting data from tensors)

In [287]:
m = torch.arange(1,101,9)

In [289]:
m, m.shape

(tensor([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100]),
 torch.Size([12]))

In [342]:
m_reshape = m.reshape(1, 6, 2)
m_reshape.shape,m_reshape

(torch.Size([1, 6, 2]),
 tensor([[[  1,  10],
          [ 19,  28],
          [ 37,  46],
          [ 55,  64],
          [ 73,  82],
          [ 91, 100]]]))

In [343]:
m_reshape[0]

tensor([[  1,  10],
        [ 19,  28],
        [ 37,  46],
        [ 55,  64],
        [ 73,  82],
        [ 91, 100]])

In [347]:
m_reshape[0][5][1]

tensor(100)

In [348]:
m_reshape[0][2][0]

tensor(37)

In [349]:
m_reshape

tensor([[[  1,  10],
         [ 19,  28],
         [ 37,  46],
         [ 55,  64],
         [ 73,  82],
         [ 91, 100]]])

In [353]:
m_reshape[:, 1, 0]

tensor([19])

In [354]:
m_reshape[:, 0, 1]

tensor([10])

In [62]:
import torch
y = torch.arange(1,10,1).reshape(1,3,3)

In [63]:
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [64]:
y[0][2][2]

tensor(9)

# Data in tensor to numpy  && Numpy to tensor

In [65]:
import torch
import numpy as np

In [75]:
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array).type(torch.float32) #Tensor by default takes Numpys data type
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [76]:
array.dtype

dtype('float64')

In [77]:
tensor.dtype

torch.float32

In [78]:
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

#Tensor to Numpy

In [79]:
tensor = torch.rand(3,2)
tensor

tensor([[0.8980, 0.8201],
        [0.1164, 0.8243],
        [0.9233, 0.3921]])

In [91]:
numpy_tensor = tensor.numpy().astype(np.float64)
numpy_tensor

array([[2.89802575, 2.82009387],
       [2.11637211, 2.82426405],
       [2.92331815, 2.39205432]])

In [92]:
#changing the tensor
tensor = tensor + 1
tensor

tensor([[3.8980, 3.8201],
        [3.1164, 3.8243],
        [3.9233, 3.3921]])

In [93]:
numpy_tensor

array([[2.89802575, 2.82009387],
       [2.11637211, 2.82426405],
       [2.92331815, 2.39205432]])

#Pytorch Reproducability

(Trying to take random out of random)
How neural network works
1. take random numbers
2. train
3. update parameters

To reduce randomness in Pytorch and neural networks

In [102]:
import torch
t1 = torch.rand(3, 4)
t2 = torch.rand(3, 4)
print(t1)
print(t2)
print(t1 == t2)

tensor([[0.7796, 0.4259, 0.8921, 0.8460],
        [0.3896, 0.0869, 0.5270, 0.1961],
        [0.2119, 0.3072, 0.8150, 0.4327]])
tensor([[0.8934, 0.4670, 0.5974, 0.2265],
        [0.1636, 0.5972, 0.2198, 0.7836],
        [0.6336, 0.0653, 0.1558, 0.0930]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


# lets make some random but reproducable seed

In [116]:
RANDOM = 40
torch.manual_seed(RANDOM)
t2 = torch.rand(3, 4)
print(t1)
print(t2)
print(t1 == t2)

tensor([[0.3679, 0.8661, 0.1737, 0.7157],
        [0.8649, 0.4878, 0.5501, 0.1318],
        [0.2897, 0.0707, 0.8016, 0.3244]])
tensor([[0.3679, 0.8661, 0.1737, 0.7157],
        [0.8649, 0.4878, 0.5501, 0.1318],
        [0.2897, 0.0707, 0.8016, 0.3244]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#Different ways of accessing GPU

In [120]:
import torch

In [121]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [125]:
tensor = torch.tensor([1, 2, 3])
tensor = tensor.to(device)
tensor

tensor([1, 2, 3])

In [129]:
#Moving tensors back to cpu
array = tensor.cpu().numpy()
array

array([1, 2, 3])

#Excises and Extra-curriculum